/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movieticket;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class Info extends javax.swing.JFrame {
 int i1,i2,i3;
 Image im;
      int arr[][][]=new int[4][4][4];
    /**
     * Creates new form Info
     */
    public Info() {
        ImageIcon img=new ImageIcon("m1.png");
        initComponents();
      im=img.getImage().getScaledInstance(lbl1.getWidth(), lbl1.getHeight(),Image.SCALE_SMOOTH);
           ImageIcon ic2=new ImageIcon(im);
      
        lbl1.setIcon(ic2);
        int r=1;
        for(int i=0;i<3;i++){
            for(int j=0;j<3;j++){
                for(int k=0;k<3;k++){
                    arr[i][j][k]=r;
                    r++;
                }
            }
        }
        
        System.out.println(d);
    }
      int d=1;
public void paintComponent(Graphics g) {
 //  super.paintComponent(g);
   g.drawImage(im, 0, 0, null);
  
}
                    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnl1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        cbdate = new javax.swing.JComboBox<>();
        cbtime = new javax.swing.JComboBox<>();
        cbmovie = new javax.swing.JComboBox<>();
        lbl1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl1.setBackground(new java.awt.Color(255, 255, 153));

        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "19/04/2020", "20/04/2020", "21/04/2020" }));
        cbdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbdateActionPerformed(evt);
            }
        });

        cbtime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11:00", "3:00", "7:00" }));
        cbtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtimeActionPerformed(evt);
            }
        });

        cbmovie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "movie 1", "movie 2", "movie 3" }));
        cbmovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmovieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(cbmovie, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(cbdate, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(cbtime, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbmovie, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbtime, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbmovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmovieActionPerformed
        // TODO add your handling code here:
         ImageIcon img=new ImageIcon("m1.png");
        i1=cbmovie.getSelectedIndex();
        String cbm = (String)cbmovie.getSelectedItem();
        System.out.println(i1);
        if(i1==0){
          img=new ImageIcon("m1.png"); 
        }
        else if(i1==1){
       img=new ImageIcon("m2.png");
        }
        else if(i1==2){
                    img=new ImageIcon("m3.png");
        }
            im=img.getImage().getScaledInstance(lbl1.getWidth(), lbl1.getHeight(),Image.SCALE_SMOOTH);
           ImageIcon ic2=new ImageIcon(im);
      
        lbl1.setIcon(ic2);
        
    }//GEN-LAST:event_cbmovieActionPerformed

    private void cbtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtimeActionPerformed
        // TODO add your handling code here:
        i3=cbtime.getSelectedIndex();
        String cbt = (String)cbtime.getSelectedItem();
        System.out.println(i3);

    }//GEN-LAST:event_cbtimeActionPerformed

    private void cbdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdateActionPerformed
        // TODO add your handling code here:
        i2=cbdate.getSelectedIndex();
        String cbd = (String)cbdate.getSelectedItem();
        System.out.println(i2);
    }//GEN-LAST:event_cbdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        d=arr[i1][i2][i3];
        System.out.println(d);

        System.out.println(d);
        new Bookedseats(d).setVisible(true);

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbdate;
    private javax.swing.JComboBox<String> cbmovie;
    private javax.swing.JComboBox<String> cbtime;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JPanel pnl1;
    // End of variables declaration//GEN-END:variables
}
